version: '3.8'

services:
  expenso-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expenso
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: [ "sh", "-c", "sleep 10 && java -jar app.jar" ]

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: expenso
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4307:3306" # <-- Exposes MySQL inside container on 3306, maps to 3307 on host
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data:
